
platform :ios, '8.0'
use_frameworks!

target ‘Demo’ do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.7.6'
    pod 'MJRefresh'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
