# Uncomment this line to define a global platform for your project

#官方Cocoapods的源
#source 'https://github.com/CocoaPods/Specs.git'

#本地私有源
#source 'https://git.oschina.net/scx/JLSpecs.git'

# 修改过得第三方库


platform :ios, '8.0'
use_frameworks!

target 'WRNetWrapper' do
    
    #swift
    pod 'Alamofire', '~> 4.4'
    pod 'SwiftyJSON'
    pod 'Kingfisher'

end
